/**
 * @file  lwipopts.h
 * @brief lwIP configuration for Pico 2W web server.
 *
 * This file is required by lwIP and configures memory pools, protocol
 * support, and the HTTP server (httpd) options.
 */

#ifndef LWIPOPTS_H
#define LWIPOPTS_H

// ─── Common settings (from pico-examples) ──────────────────────────────────

// Allow override from CMake
#ifndef NO_SYS
#define NO_SYS 1 // No OS — bare-metal (poll mode)
#endif

#ifndef LWIP_SOCKET
#define LWIP_SOCKET 0
#endif

#ifndef LWIP_NETCONN
#define LWIP_NETCONN 0
#endif

#define MEM_LIBC_MALLOC 0
#define MEM_ALIGNMENT   4
#define MEM_SIZE        (16 * 1024) // 16 KB heap for lwIP

// ─── Protocol support ──────────────────────────────────────────────────────

#define LWIP_ARP      1
#define LWIP_ETHERNET 1
#define LWIP_ICMP     1 // ping support
#define LWIP_RAW      1
#define LWIP_TCP      1
#define LWIP_UDP      1
#define LWIP_DHCP     1
#define LWIP_DNS      1
#define LWIP_AUTOIP   0
#define LWIP_IGMP     0

// ─── TCP tuning ─────────────────────────────────────────────────────────────

#define TCP_WND             (4 * TCP_MSS)
#define TCP_MSS             1460
#define TCP_SND_BUF         (4 * TCP_MSS)
#define TCP_SND_QUEUELEN    ((4 * (TCP_SND_BUF) + (TCP_MSS - 1)) / (TCP_MSS))
#define MEMP_NUM_TCP_PCB    5
#define MEMP_NUM_TCP_SEG    32
#define LWIP_TCP_KEEPALIVE  1
#define LWIP_NETIF_TX_SINGLE_PBUF 1

// ─── Pbuf pool ──────────────────────────────────────────────────────────────

#define PBUF_POOL_SIZE 24

// ─── HTTPD (Web Server) ────────────────────────────────────────────────────

#define LWIP_HTTPD_CGI            1 // Enable CGI callbacks
#define LWIP_HTTPD_SSI            1 // Enable Server-Side Includes
#define LWIP_HTTPD_SSI_MULTIPART  1 // SSI in sub-pages
#define LWIP_HTTPD_SUPPORT_POST   0 // We only use GET
#define LWIP_HTTPD_SSI_INCLUDE_TAG 0 // Don't include the SSI tag in output
#define LWIP_HTTPD_MAX_TAG_NAME_LEN  32
#define LWIP_HTTPD_MAX_TAG_INSERT_LEN 1024

// Use custom fsdata file (generated by pico_set_lwip_httpd_content)
#define HTTPD_FSDATA_FILE "pico_fsdata.inc"

// Enable dynamic headers (Content-Type based on file extension)
#define LWIP_HTTPD_DYNAMIC_HEADERS 1

// ─── Timeouts ──────────────────────────────────────────────────────────────

#define LWIP_HTTPD_KILL_OLD_ON_CONNECTIONS_EXCEEDED 1
#define HTTPD_MAX_RETRIES      4
#define HTTPD_POLL_INTERVAL    4

// ─── Stats / Debug ─────────────────────────────────────────────────────────

#define LWIP_STATS         0
#define LWIP_STATS_DISPLAY 0

// Debug output (uncomment to enable per-module debug)
// #define LWIP_DEBUG 1
// #define HTTPD_DEBUG LWIP_DBG_ON
// #define TCP_DEBUG   LWIP_DBG_ON

#endif // LWIPOPTS_H
