#!/usr/bin/env python3
"""
makefsdata.py — Compile web assets (www/) into a C source file (fsdata.c)
for lwIP's httpd file system.

Usage:
    python makefsdata.py

This reads all files from the www/ directory and generates fsdata.c,
which contains the file data as C arrays that lwIP httpd serves.

The generated file follows lwIP's custom fsdata format:
  - Each file is stored as a linked list node (struct fsdata_file)
  - File names are stored as null-terminated strings
  - File data is stored as const unsigned char arrays
"""

import os
import sys

WWW_DIR = "www"
OUTPUT_FILE = "fsdata.c"

# File extension to Content-Type mapping for HTTP headers
CONTENT_TYPES = {
    ".html": "text/html",
    ".shtml": "text/html",
    ".css": "text/css",
    ".js": "application/javascript",
    ".json": "application/json",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".gif": "image/gif",
    ".ico": "image/x-icon",
    ".svg": "image/svg+xml",
    ".txt": "text/plain",
}


def file_var_name(filepath):
    """Convert a file path to a valid C variable name."""
    name = filepath.replace("/", "_").replace("\\", "_").replace(".", "_")
    name = name.replace("-", "_")
    return name


def to_c_array(data):
    """Convert binary data to a C array initializer string."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_vals},")
    return "\n".join(lines)


def main():
    if not os.path.isdir(WWW_DIR):
        print(f"Error: '{WWW_DIR}' directory not found.", file=sys.stderr)
        print(f"Create a '{WWW_DIR}' directory with your web files.", file=sys.stderr)
        sys.exit(1)

    # Collect all files
    files = []
    for root, dirs, filenames in os.walk(WWW_DIR):
        for filename in sorted(filenames):
            filepath = os.path.join(root, filename)
            # Convert to web path (e.g., "www/index.shtml" -> "/index.shtml")
            webpath = "/" + os.path.relpath(filepath, WWW_DIR).replace("\\", "/")
            files.append((webpath, filepath))

    if not files:
        print(f"Warning: No files found in '{WWW_DIR}/'", file=sys.stderr)
        sys.exit(1)

    print(f"Generating {OUTPUT_FILE} from {len(files)} files:")

    with open(OUTPUT_FILE, "w") as out:
        out.write("/*\n")
        out.write(f" * {OUTPUT_FILE} — Auto-generated by makefsdata.py\n")
        out.write(" * DO NOT EDIT — regenerate with: python makefsdata.py\n")
        out.write(" */\n\n")
        out.write('#include "lwip/apps/fs.h"\n')
        out.write('#include "lwip/def.h"\n\n')

        # Generate data arrays for each file
        for webpath, filepath in files:
            varname = file_var_name(webpath)
            with open(filepath, "rb") as f:
                data = f.read()

            print(f"  {webpath} ({len(data)} bytes)")

            # File name as null-terminated char array
            out.write(f"/* {webpath} */\n")
            name_bytes = webpath.encode("ascii") + b"\x00"
            out.write(f"static const unsigned char data_{varname}_name[] = {{\n")
            out.write(to_c_array(name_bytes))
            out.write(f"\n}};\n\n")

            # File content
            out.write(f"static const unsigned char data_{varname}[] = {{\n")
            out.write(to_c_array(data))
            out.write(f"\n}};\n\n")

        # Generate the linked list of fsdata_file structs
        out.write("\n/* File system structure */\n\n")

        prev_var = "NULL"
        for i, (webpath, filepath) in enumerate(files):
            varname = file_var_name(webpath)
            with open(filepath, "rb") as f:
                data = f.read()

            struct_name = f"file_{varname}"

            # Determine if file has SSI tags (.shtml extension)
            _, ext = os.path.splitext(webpath)
            # lwIP uses flags: FS_FILE_FLAGS_HEADER_INCLUDED = 0x01,
            #                  FS_FILE_FLAGS_HEADER_PERSISTENT = 0x02,
            #                  FS_FILE_FLAGS_SSI = 0x04
            flags = 0
            if ext == ".shtml":
                flags |= 0x04  # FS_FILE_FLAGS_SSI

            out.write(f"const struct fsdata_file {struct_name}[] = {{{{")
            out.write(f" {prev_var},")
            out.write(f" data_{varname}_name,")
            out.write(f" data_{varname},")
            out.write(f" sizeof(data_{varname}),")
            out.write(f" {flags}")
            out.write(" }};\n")

            prev_var = struct_name

        # The root file pointer (last file in the chain)
        out.write(f"\n#define FS_ROOT {prev_var}\n")
        out.write(f"#define FS_NUMFILES {len(files)}\n")

    print(f"\nGenerated {OUTPUT_FILE} successfully.")


if __name__ == "__main__":
    main()
